// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8JAAj1VfDVY_BaTnj71GIKuhJpX9NiU',
    appId: '1:453171651477:web:b063a93aeddc69d28ccc9c',
    messagingSenderId: '453171651477',
    projectId: 'sshchatfitur',
    authDomain: 'sshchatfitur.firebaseapp.com',
    storageBucket: 'sshchatfitur.firebasestorage.app',
    measurementId: 'G-2DWCB01VNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtCGvN1HZT8Rb2e-Jj7jFFJDLsvohVGo',
    appId: '1:453171651477:android:8c85e873d51e34e58ccc9c',
    messagingSenderId: '453171651477',
    projectId: 'sshchatfitur',
    storageBucket: 'sshchatfitur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsytgpg0dfCvnwW2tyZ-gxqpLEMm6VJio',
    appId: '1:453171651477:ios:6b2d312c5b0ce95e8ccc9c',
    messagingSenderId: '453171651477',
    projectId: 'sshchatfitur',
    storageBucket: 'sshchatfitur.firebasestorage.app',
    iosBundleId: 'com.example.sshAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsytgpg0dfCvnwW2tyZ-gxqpLEMm6VJio',
    appId: '1:453171651477:ios:6b2d312c5b0ce95e8ccc9c',
    messagingSenderId: '453171651477',
    projectId: 'sshchatfitur',
    storageBucket: 'sshchatfitur.firebasestorage.app',
    iosBundleId: 'com.example.sshAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo8JAAj1VfDVY_BaTnj71GIKuhJpX9NiU',
    appId: '1:453171651477:web:4b80339683e52fc68ccc9c',
    messagingSenderId: '453171651477',
    projectId: 'sshchatfitur',
    authDomain: 'sshchatfitur.firebaseapp.com',
    storageBucket: 'sshchatfitur.firebasestorage.app',
    measurementId: 'G-JS0MDSWVLJ',
  );
}
